spring:
  config:
    import: >
      classpath:application-port.yml,
      classpath:application-db.yml,
      classpath:application-mq-int.yml,
      classpath:application-mq-ext.yml
      
uae:
  gateway:
    sender-system: "EK, EY, QR"
    all-airline: false
    file-storage:
      error: file://./messages/ERROR/
    autoresponder:
      enabled: false
      return-code: 8501
      return-description : BOARD IF DOCS OK
    request-identifier: 2800
    request:
      max:
        redelivery:
          attempt: 0
      delay:
        pattern: 0:10000
    app:
      listOfUAEPorts: AUH,DXB,SHJ,RKT
      destinationID: 3200
      originID: 1000
      agencyIdentifier: "00000000"
      city: AUH
      country: ARE
      listOfPassengerRefs: 001,002,003,004,005
      international:
        countryOfLastFirstForeignPort: ARE
      messageIdSequence: GATEWAY_MESSAGE_ID_SEQ
      movementIdSequence: GATEWAY_MOVEMENT_ID_SEQ
    audit:
      isTraceEnabled: true		